<a href="https://colab.research.google.com/github/AvishekPritom/Pandas-learning-path/blob/main/Pandas_05_How_to_create_new_columns_derived_from_existing_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

air_quality-_no2 Dataset loading....

In [ ]:
air_quality = pd.read_csv('/content/air_quality_no2.csv', index_col=0, parse_dates=True)

In [ ]:
air_quality.head()

                     station_antwerp  station_paris  station_london
datetime
2019-05-07 02:00:00              NaN            NaN            23.0
2019-05-07 03:00:00             50.5           25.0            19.0
2019-05-07 04:00:00             45.0           27.7            19.0
2019-05-07 05:00:00              NaN           50.4            16.0
2019-05-07 06:00:00              NaN           61.9             NaN

Note
>index_col=0 -> Use the first column as the DataFrame index.

>parse_dates=True ->This tells pandas: “Convert date-like text into datetime objects.”

#How to create new columns derived from existing columns

I want to express the
𝑁⁢𝑂2
 concentration of the station in London in mg/m
3
.

In [ ]:
air_quality['london_mg_per_cubic'] = air_quality['station_london'] * 1.882 # which is the conversion factor

In [ ]:
air_quality['london_mg_per_cubic'].head()

datetime
2019-05-07 02:00:00    43.286
2019-05-07 03:00:00    35.758
2019-05-07 04:00:00    35.758
2019-05-07 05:00:00    30.112
2019-05-07 06:00:00       NaN
Name: london_mg_per_cubic, dtype: float64

Note
>To create a new column, use the square brackets [] with the new column name at the left side of the assignment.The calculation of the values is done element-wise. This means all values in the given column are multiplied by the value 1.882 at once. You do not need to use a loop to iterate each of the rows!

I want to check the ratio of the values in Paris versus Antwerp and save the result in a new column.

In [ ]:
air_quality['rario_paris_antwerp'] = air_quality['station_paris'] / air_quality['station_antwerp']

In [ ]:
air_quality['rario_paris_antwerp'].head()

datetime
2019-05-07 02:00:00         NaN
2019-05-07 03:00:00    0.495050
2019-05-07 04:00:00    0.615556
2019-05-07 05:00:00         NaN
2019-05-07 06:00:00         NaN
Name: rario_paris_antwerp, dtype: float64

Note
>The calculation is again element-wise, so the / is applied for the values in each row.

I want to rename the data columns to the corresponding station identifiers used by OpenAQ.

In [ ]:
air_quality_renamed = air_quality.rename(
    columns = {
        'station_antwerp': 'BETR801',
        'station_paris': 'FR04014',
        'station_london': 'London Westminster',
    }
)

In [ ]:
air_quality_renamed.head()

,BETR801,FR04014,London Westminster,london_mg_per_cubic,rario_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,35.758,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,35.758,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,30.112,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

Note
>The rename() function can be used for both row labels and column labels. Provide a dictionary with the keys the current names and the values the new names to update the corresponding names.

Note
>The mapping should not be restricted to fixed names only, but can be a mapping function as well. For example, converting the column names to lowercase letters can be done using a function as well:

In [ ]:
air_quality_renamed_lower = air_quality_renamed.rename(columns=str.lower)

In [ ]:
air_quality_renamed_lower.head()

,betr801,fr04014,london westminster,london_mg_per_cubic,rario_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,35.758,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,35.758,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,30.112,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

**Remenber**



*   Create a new column by assigning the output to the DataFrame with a new column name in between the [].
*  Operations are element-wise, no need to loop over rows
* Use rename with a dictionary or function to rename row labels or column names.